name: oyt_front_core
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/nestorsgarzonc

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  hive: ^2.2.3
  http: ^0.13.5
  intl: ^0.18.0
  socket_io_client: ^2.0.0
  firebase_core: ^2.4.0
  firebase_messaging: ^14.2.0
  firebase_messaging_web: ^3.2.10
  firebase_core_web: ^2.0.2
  image_picker: ^0.8.6
  image_picker_for_web: ^2.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/lottie/
