name: oyt_front_core
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/nestorsgarzonc

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  hive: ^2.2.3
  http: ^0.13.5
  intl: ^0.17.0
  socket_io_client: ^2.0.0

  firebase_core: ^1.19.0
  firebase_messaging: ^11.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/lottie/
