name: oyt_front_core
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/nestorsgarzonc

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  collection: ^1.16.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_core_web: ^2.1.0
  firebase_core: ^2.4.1
  firebase_messaging_web: ^3.2.11
  firebase_messaging: ^14.2.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  font_awesome_flutter: ^10.3.0
  go_router: ^6.0.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  http: ^0.13.5
  image_picker_for_web: ^2.1.10
  image_picker: ^0.8.6
  intl: ^0.18.0
  lottie: ^2.2.0
  riverpod: ^2.1.3
  socket_io_client: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
